### ISSUE TITLE
Version 3.1.1 is not building techradar

### ISSUE THREAD

**Issue by Karreg** [AOEpeople/aoe_technology_radar#106]
Hello,

I have upgraded my radar with the latest release, and now the techradar is not building, with 2 separate issues related to the 2 new features.

I have updated the dependencies with :

```bash
yarn upgrade && yarn install
```

Then I build the radar with the following commands.

- First issue is about html-sanitize when running `yarn aoe_technology_radar-buildRadar`

```
yarn aoe_technology_radar-buildRadar
yarn run v1.22.15
warning package.json: No license field
$ /workspaces/techradar/node_modules/.bin/aoe_technology_radar-buildRadar
warning ../../package.json: No license field
$ react-scripts build
Creating an optimized production build...
Failed to compile.

/workspaces/techradar/node_modules/aoe_technology_radar/src/components/PageHelp/PageHelp.tsx
TypeScript error in /workspaces/techradar/node_modules/aoe_technology_radar/src/components/PageHelp/PageHelp.tsx(2,26):
Could not find a declaration file for module 'sanitize-html'. '/workspaces/techradar/node_modules/sanitize-html/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sanitize-html` if it exists or add a new declaration (.d.ts) file containing `declare module 'sanitize-html';`  TS7016

    1 | import React from "react";
  > 2 | import sanitizeHtml from 'sanitize-html';
      |                          ^
    3 | import HeroHeadline from "../HeroHeadline/HeroHeadline";
    4 | import Fadeable from "../Fadeable/Fadeable";
    5 | import SetTitle from "../SetTitle";


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- Second issue appears with `yarn aoe_technology_radar-createStaticFiles`:

```
yarn aoe_technology_radar-createStaticFiles
yarn run v1.22.15
warning package.json: No license field
$ /workspaces/techradar/node_modules/.bin/aoe_technology_radar-createStaticFiles
starting static
/workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/createStaticFiles.js:49
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/workspaces/techradar/build/config.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at checkAttributes (/workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:112:24)
    at /workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:137:97
    at step (/workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:63:23)
    at Object.next (/workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:44:53)
    at /workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:34:12)
    at /workspaces/techradar/node_modules/aoe_technology_radar/dist_scripts/scripts/generateJson/radar.js:127:81 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/workspaces/techradar/build/config.json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Regards.

**Comment by bastianccm** [comment]
Fixed in release 3.1.2
